version: "3"

services:
  bitbucket:
    build:
      context: ./
    ports:
      - "${BITBUCKET_HTTP_PORT}:7990"
    environment:
      - BITBUCKET_DISPLAYNAME
      - BITBUCKET_BASEURL
      - BITBUCKET_EMAIL
      - BITBUCKET_LICENSE
      - BITBUCKET_HTTP_PORT
      - BITBUCKET_USER
      - BITBUCKET_PASSWORD
      - BITBUCKET_USER_DISPLAYNAME
      - CATALINA_CONNECTOR_PROXYNAME
      - CATALINA_CONNECTOR_PROXYPORT
      - CATALINA_CONNECTOR_SCHEME
      - CATALINA_CONNECTOR_SECURE
