= README

Docker Image image:https://images.microbadger.com/badges/image/softwarecraftsmen/atlassian-bitbucket-base.svg[link="https://microbadger.com/images/softwarecraftsmen/atlassian-bitbucket-base" alt="atlassian-bitbucket-base image layers"]
image:https://images.microbadger.com/badges/version/softwarecraftsmen/atlassian-bitbucket-base.svg[link="https://microbadger.com/images/softwarecraftsmen/atlassian-bitbucket-base" alt="atlassian-bitbucket-base image layers"]

This image provides a [Bitbucket Server](https://www.atlassian.com/software/bitbucket/server) with an embedded database which is sufficient for demo and evaluation purpose.
However, for production it is advised to use one of the [supported external databases](https://confluence.atlassian.com/bitbucketserver/connecting-bitbucket-server-to-an-external-database-776640378.html) (e.g. PostgreSQL). This image has a yet minimalistic support for configuring such a database by extending from this image.

The following instructions show how to build and run Bitbucket Server.

== Prepare a docker host

[source,shell]
----
docker-machine create --driver virtualbox atlassian <1>
docker-machine start atlassian <2>
eval `docker-machine env atlassian` <3>
----
1. Create a docker machine (once only)
2. Start the docker machine
3. Setup the docker client to use the docker-machine

== Build the image

.Build with VCS information built-in as docker label

[source,shell]
----
docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) -t softwarecraftsmen/atlassian-bitbucket-base .
----

=== Publish to Docker Hub

Tag the git repository using the bitbucket version number as tag

[source,shell]
----
git tag <bitbucket-version>
git push origin master --tags
----

== Run a Bitbucket Server instance

[source,shell]
----
docker pull softwarecraftsmen/atlassian-bitbucket-base
docker run -d --name bitbucket-server -p 7990:7990 softwarecraftsmen/atlassian-bitbucket-base
----

The first time container startup takes some time as the installation and configuration process is continuing.
So be patient until the start page for license registration can be opened.

To open Bitbucket Server start page on Mac OSX run `open http://$(docker-machine ip atlassian):7990`from the shell:

IMPORTANT:
While the setup completes, the setup wizard will ask for an administrator account setup.
The username and password must match the settings provided by the environment variables `BITBUCKET_USER` and `BITBUCKET_PASSWORD`.

== Extend this image

=== Use an external database

For replacing the internal embedded database we just have to add a [bitbucket.properties](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-config-properties-776640155.html) file as ${BITBUCKET_HOME}/bitbucket.properties.template to the image.
It will be moved to `$BITBUCKET_HOME/shared/`.

[source,shell]
----
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://postgresdb:5432/bitbucket
----

The extending image can add this file in its `Dockerfile` like

[source,shell]
----
ADD bitbucket.properties.template ${BITBUCKET_HOME}/bitbucket.properties.template
----

This base image offers a few environment variables especially for setting sensitive settings such as password or license keys that should not be committed to the repository. These are automatically written into their respective property keys in `bitbucket.properties`.
These are better set through environment variables and passed to the container rather than hard coded them into `bitbucket.properties`.

== Environment Variables

During the first start of the container a few environment variables are considered to customize the container.

The subset of supported [bitbucket.properties](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-config-properties-776640155.html) is as follows.



.Variables
|===
|Environment |`bitbucket.properties |Comment

|`BITBUCKET_LICENSE`
|`setup.license`
|Required, no default provided.

|`BITBUCKET_USER`
|`setup.sysadmin.username`
|Column 3, row 2

|`BITBUCKET_PASSWORD`
|`setup.sysadmin.password`
|Column 3, row 3

|`BITBUCKET_JDBC_USER`
|`jdbc.user`
|Column 3, row 4

|`BITBUCKET_JDBC_PASSWORD`
|`jdbc.password`
|Column 3, row 5

|`BITBUCKET_DISPLAYNAME`
|`setup.displayName`
|Column 3, row 6

|`BITBUCKET_BASEURL`
|`setup.baseUrl`
|Column 3, row 7

|`BITBUCKET_USER_DISPLAYNAME`
|`setup.sysadmin.displayName`
|Column 3, row 8

|`BITBUCKET_EMAIL`
|`setup.sysadmin.emailAddress`
|Column 3, row 9
|===

== Backup

See [Using Bitbucket Server DIY Backup](https://confluence.atlassian.com/bitbucketserver/using-bitbucket-server-diy-backup-776640056.html).
